insert into public.clinics (
  name,
  province,
  district,
  area,
  facility_type,
  address,
  services_offered,
  latitude,
  longitude
) values
(
  'UCT Private Academic Hospital',
  'Western Cape',
  'City of Cape Town',
  'Cape Town',
  'hospital',
  null,
  'heart_and_lung_centre;paediatric_unit;uterine_fibroid_embolisation;thyroid_clinic;orthopaedic_specialised_unit;cape_pulmonology;intensive_care_unit;centre_for_diabetes_&_endocrinology_(cde',
  -33.94205,
  18.46331
),
(
  'Kwaggafontein Community Health Centre',
  'Mpumalanga',
  'Nkangala',
  'Kwaggafontein',
  'clinic',
  null,
  null,
  -25.31062,
  28.94353
),
(
  'Matthew Goniwe Clinic',
  'Western Cape',
  'City of Cape Town',
  'Cape Town',
  'clinic',
  null,
  null,
  -34.04417,
  18.70574
),
(
  'Ngwelezana Hospital',
  'KwaZulu-Natal',
  'King Cetshwayo',
  'Empangeni',
  'hospital',
  null,
  'general;paediatrics;critical_care;ophthalmology;psychiatry;audiology;dietetics;dental;social_worker;arv_clinic',
  -28.77924,
  31.86489
),
(
  'Pefferville Clinic',
  'Eastern Cape',
  'Buffalo City',
  'East London',
  'clinic',
  null,
  'emergency_services;ambulance_services;medical_practitioners;dental_practitioners;hiv_counseling;depression',
  -33.01235,
  27.88067
),
(
  'Site B Community Health Clinic',
  'Western Cape',
  'City of Cape Town',
  'Khayelitsha',
  'clinic',
  null,
  'maternity;hiv_and_aids_treatment;dentistry;chronic_illness;emergency_services;immunisation;mental_health;occupational_health;sexually_transmitted_infections;tuberculosis_treatment',
  -34.02819,
  18.66550
),
(
  'Site B Male Clinic',
  'Western Cape',
  'City of Cape Town',
  'Khayelitsha',
  'clinic',
  null,
  'circumcision_counselling;general_hiv_care;hiv_testing;sti_assessment_and_treatment;tb_assessment_and_treatment',
  -34.02640,
  18.66605
),
(
  'Macabuzela Clinic',
  'KwaZulu-Natal',
  'uMkhanyakude',
  'Hluhluwe',
  'clinic',
  null,
  'maternity;general;emergency',
  -28.02793,
  32.15993
),
(
  'Medicare24',
  'Gauteng',
  'Ekurhuleni',
  'Boksburg',
  'clinic',
  null,
  'general;occupational;orthodontics;psychiatry;radiology',
  -26.17839,
  28.24573
),
(
  'Rooihuiskraal Clinic',
  'Gauteng',
  'City of Tshwane',
  'Centurion',
  'clinic',
  null,
  null,
  -25.89333,
  28.15467
),
(
  'Berario Clinic',
  'Gauteng',
  'City of Johannesburg',
  'Randburg',
  'clinic',
  null,
  'general;child_health;reproductive_health;stis',
  -26.13610,
  27.95211
),
(
  'Delportshoop Clinic',
  'Northern Cape',
  'Frances Baard',
  'Delportshoop',
  'clinic',
  null,
  'general;maternity;hiv_and_aids',
  -28.41983,
  24.31254
),
(
  'V Shumane Clinic',
  'Eastern Cape',
  'Sarah Baartman',
  'Grahamstown',
  'clinic',
  null,
  null,
  -33.29620,
  26.54642
),
(
  'DR T.J Women''s Clinic Tembisa',
  'Gauteng',
  'Ekurhuleni',
  'Tembisa',
  'clinic',
  null,
  'general;gynaecology;vaccination',
  -26.00164,
  28.21289
),
(
  'Wesfleur Private Clinic',
  'Western Cape',
  'City of Cape Town',
  'Cape Town',
  'clinic',
  null,
  null,
  -33.56526,
  18.49420
),
(
  'Medicross Mossel Bay',
  'Western Cape',
  'Garden Route',
  'Mossel Bay',
  'clinic',
  null,
  'dentistry;family_med',
  -34.18383,
  22.11385
),
(
  'Langenhoven Park Clinic',
  'Free State',
  'Mangaung',
  'Bloemfontein',
  'clinic',
  null,
  null,
  -29.09778,
  26.15596
),
(
  'Duncan Village Community Health Clinic',
  'Eastern Cape',
  'Buffalo City',
  'East London',
  'clinic',
  null,
  'anti-retroviral_treatment_services_(arvs);tuberculosis_(tb)_clinic;basic_gynaecology_services;family_planning_services;pharmacy_services;x-ray_services',
  -33.00774,
  27.88609
),
(
  'Dr Winston Torres Clinic',
  'Northern Cape',
  'Frances Baard',
  'Kimberley',
  'clinic',
  null,
  'general;emergency;maternity;chronic',
  -28.66276,
  24.71565
),
(
  'Daniel Ngatane Clinic',
  'Free State',
  'Mangaung',
  'Botshabelo',
  'clinic',
  null,
  'general;chronic;maternity',
  -29.22073,
  26.67053
);